/** List of actions authorized via roles. See Authorizations Mixin. */
export enum AuthorizedActions {
  STAFF_BREADCRUMBS,
  STAFF_PAYMENT,
  FILE_AND_PAY,
  BLANK_COMPLETING_PARTY,
  BLANK_CERTIFY_STATE,
  SKIP_ADD_PERSON_MESSAGE_BOX,
  EDITABLE_EMAIL_ADDRESS,
  EDITABLE_COMPLETING_PARTY,
  EDITABLE_CERTIFIED_NAME,
  ALTERNATE_CERTIFY_MESSAGE,
}
